### ISSUE TITLE
thisArg = this ? it makes no sense then, remove it everywhere

### ISSUE THREAD

**Issue by Arkant** [mneokvsenorm/myArray#20]
https://github.com/mneokvsenorm/myArray/blob/08949360630bc6644edee41d5b573bf16fb0a6c6/src/index.js#L97

**Comment by mneokvsenorm** [comment]
Why?

**Comment by motifej** [comment]
@Arkant explain plz why?

**Comment by Arkant** [comment]
From MDN. If thisArg is not provided, then undefined will be used as its this value:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
If a thisArg parameter is provided to map, it will be used as callback's this value. Otherwise, the value undefined will be used as its this value. The this value ultimately observable by callback is determined according to the usual rules for determining the this seen by a function.
